# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KxTeRMDaooc5wI6d8DNnXlk1pveOsqoI
"""

# step 1 : import library
import pandas as pd

# step 2 : import data
admission = pd.read_csv('https://raw.githubusercontent.com/YBIFoundation/Dataset/main/Admission%20Chance.csv')

admission.head()

admission.info()

admission.describe()

# step 3:define target (y) and  features(x)

admission.columns

y = admission ['Serial No']

x = admission.drop(['Serial No','Chance of Admit '],axis=1)

# step 4 :train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,train_size=0.7,random_state=2529)

X_train.shape,X_test.shape,y_train.shape,y_test.shape

# step 5:select model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

# step 6 : train  or fit model
model.fit(X_train,y_train)

model.intercept_

model.coef_

# step 7:predict model
y_pred = model.predict(X_test)

y_pred

# step 8 : model accuracy
from sklearn.metrics import mean_absolute_error,mean_absolute_percentage_error,mean_squared_error

mean_absolute_percentage_error(y_test,y_pred)

mean_squared_error(y_test,y_pred)